repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Aktuelle Version pr√ºfen!
    hooks:
      - id: black
        args: ["--line-length=110"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "110"]

  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: python
        types: [python]
        args: ["--in-place", "--wrap-summaries=110", "--wrap-descriptions=110"]
